// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo7_-bW49WLtIUGdllgS2suu0LJHGkDec',
    appId: '1:625951911067:web:74cdbc821c52cccd412a3e',
    messagingSenderId: '625951911067',
    projectId: 'chat-with-me-f4eae',
    authDomain: 'chat-with-me-f4eae.firebaseapp.com',
    storageBucket: 'chat-with-me-f4eae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQJiQ7lwOCIpBiNlWMAl9K6hu-k9mrpeI',
    appId: '1:625951911067:android:b1bbb740f8b0cffe412a3e',
    messagingSenderId: '625951911067',
    projectId: 'chat-with-me-f4eae',
    storageBucket: 'chat-with-me-f4eae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHZPu2DgUybqK2Lv_qHW5ACW6bFAzliUg',
    appId: '1:625951911067:ios:03e8ca0b1db81cb7412a3e',
    messagingSenderId: '625951911067',
    projectId: 'chat-with-me-f4eae',
    storageBucket: 'chat-with-me-f4eae.appspot.com',
    androidClientId: '625951911067-i4hgi5hm20lstoamfhf53ku9s5ca6894.apps.googleusercontent.com',
    iosClientId: '625951911067-88gc8e8v4vm8s1pg6ovltecd7hpso17s.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHZPu2DgUybqK2Lv_qHW5ACW6bFAzliUg',
    appId: '1:625951911067:ios:03e8ca0b1db81cb7412a3e',
    messagingSenderId: '625951911067',
    projectId: 'chat-with-me-f4eae',
    storageBucket: 'chat-with-me-f4eae.appspot.com',
    androidClientId: '625951911067-i4hgi5hm20lstoamfhf53ku9s5ca6894.apps.googleusercontent.com',
    iosClientId: '625951911067-88gc8e8v4vm8s1pg6ovltecd7hpso17s.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat1',
  );
}
